version: 0.2

phases:
  build:
    commands:
      - docker build -t myimage .
  post_build:
    commands:
      - docker pull anchore/cli
      - docker run -d -v $(pwd):/source-dir -v /var/run/docker.sock:/var/run/docker.sock --name anchore anchore/cli:latest
      - docker exec anchore anchore feeds sync
      - docker exec anchore anchore evaluate check myimage
      - docker exec anchore anchore analyze --image myimage --dockerfile /source-dir/Dockerfile

artifacts:
  files:
    - '**/*'
